---
# Check RedHat/CentOS epel repository
- name: Check if epel_repo exist for RedHat/CentOS
  shell: "yum repolist 2>/dev/null | grep 'epel' && echo 'true'|| echo 'false'"
  args:
    warn: false
  register: is_epel_repo_installed
  changed_when: false
  tags:
    - check-epel-repo

# Define facts to manage epel repository
- name: Fail when EPEL repository is not installed
  fail:
    msg: "EPEL repository is not installed, you could use 'christiangda.epel_repo' galaxy role in your playbook"
  when: is_epel_repo_installed.stdout is search('false')

- name: Install "{{ cli_dependencies_packages }}" dependencies from EPEL repository
  yum:
    name: "{{ cli_dependencies_packages }}"
    state: present
  tags:
    - install

- name: Install {{ cli_package }}
  pip:
    name: "{{ cli_package }}"
    state: present
  tags:
    - install
